export const ActionTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  GET_PRODUCTS: 'GET_PRODUCTS',
  SET_CATEGORIES: 'SET_CATEGORIES',
  GET_CATEGORIES: 'GET_CATEGORIES',
  SET_SUBCAT: 'SET_SUBCAT',
  GET_SUBCAT: 'GET_SUBCAT',
  SET_PAGE: 'SET_PAGE',
  SET_ACTIVE_CAT: 'SET_ACTIVE_CAT',
  SELECTED_PRODUCT: 'SELECTED_PRODUCT',
  REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
};
